<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (!Schema::hasTable('municipios')) {
            Schema::create('municipios', function (Blueprint $table) {
                $table->id();
                $table->string('codigo', 10);
                $table->string('nombre', 100);
                $table->string('departamento', 100);
            });
        }

        DB::table('municipios')->insert([
            ['id' => 12, 'codigo' => '05002', 'nombre' => 'Abejorral', 'departamento' => 'Antioquia'],
            ['id' => 13, 'codigo' => '05004', 'nombre' => 'Abriaqui', 'departamento' => 'Antioquia'],
            ['id' => 14, 'codigo' => '05021', 'nombre' => 'Alejandria', 'departamento' => 'Antioquia'],
            ['id' => 15, 'codigo' => '05030', 'nombre' => 'Amaga', 'departamento' => 'Antioquia'],
            ['id' => 16, 'codigo' => '05031', 'nombre' => 'Amalfi', 'departamento' => 'Antioquia'],
            ['id' => 17, 'codigo' => '05034', 'nombre' => 'Andes', 'departamento' => 'Antioquia'],
            ['id' => 18, 'codigo' => '05036', 'nombre' => 'Angelopolis', 'departamento' => 'Antioquia'],
            ['id' => 19, 'codigo' => '05038', 'nombre' => 'Angostura', 'departamento' => 'Antioquia'],
            ['id' => 20, 'codigo' => '05040', 'nombre' => 'Anori', 'departamento' => 'Antioquia'],
            ['id' => 21, 'codigo' => '05044', 'nombre' => 'Anza', 'departamento' => 'Antioquia'],
            ['id' => 22, 'codigo' => '05045', 'nombre' => 'Apartado', 'departamento' => 'Antioquia'],
            ['id' => 23, 'codigo' => '05051', 'nombre' => 'Arboletes', 'departamento' => 'Antioquia'],
            ['id' => 24, 'codigo' => '05055', 'nombre' => 'Argelia', 'departamento' => 'Antioquia'],
            ['id' => 25, 'codigo' => '05059', 'nombre' => 'Armenia', 'departamento' => 'Antioquia'],
            ['id' => 26, 'codigo' => '05079', 'nombre' => 'Barbosa', 'departamento' => 'Antioquia'],
            ['id' => 27, 'codigo' => '05088', 'nombre' => 'Bello', 'departamento' => 'Antioquia'],
            ['id' => 28, 'codigo' => '05086', 'nombre' => 'Belmira', 'departamento' => 'Antioquia'],
            ['id' => 29, 'codigo' => '05091', 'nombre' => 'Betania', 'departamento' => 'Antioquia'],
            ['id' => 30, 'codigo' => '05093', 'nombre' => 'Betulia', 'departamento' => 'Antioquia'],
            ['id' => 31, 'codigo' => '05107', 'nombre' => 'Briceño', 'departamento' => 'Antioquia'],
            ['id' => 32, 'codigo' => '05113', 'nombre' => 'Buritica', 'departamento' => 'Antioquia'],
            ['id' => 33, 'codigo' => '05138', 'nombre' => 'Cañasgordas', 'departamento' => 'Antioquia'],
            ['id' => 34, 'codigo' => '05120', 'nombre' => 'Caceres', 'departamento' => 'Antioquia'],
            ['id' => 35, 'codigo' => '05125', 'nombre' => 'Caicedo', 'departamento' => 'Antioquia'],
            ['id' => 36, 'codigo' => '05129', 'nombre' => 'Caldas', 'departamento' => 'Antioquia'],
            ['id' => 37, 'codigo' => '05134', 'nombre' => 'Campamento', 'departamento' => 'Antioquia'],
            ['id' => 38, 'codigo' => '05142', 'nombre' => 'Caracoli', 'departamento' => 'Antioquia'],
            ['id' => 39, 'codigo' => '05145', 'nombre' => 'Caramanta', 'departamento' => 'Antioquia'],
            ['id' => 40, 'codigo' => '05147', 'nombre' => 'Carepa', 'departamento' => 'Antioquia'],
            ['id' => 41, 'codigo' => '05150', 'nombre' => 'Carolina', 'departamento' => 'Antioquia'],
            ['id' => 42, 'codigo' => '05154', 'nombre' => 'Caucasia', 'departamento' => 'Antioquia'],
            ['id' => 43, 'codigo' => '05172', 'nombre' => 'Chigorodo', 'departamento' => 'Antioquia'],
            ['id' => 44, 'codigo' => '05190', 'nombre' => 'Cisneros', 'departamento' => 'Antioquia'],
            ['id' => 45, 'codigo' => '05101', 'nombre' => 'Ciudad Bolivar', 'departamento' => 'Antioquia'],
            ['id' => 46, 'codigo' => '05197', 'nombre' => 'Cocorna', 'departamento' => 'Antioquia'],
            ['id' => 47, 'codigo' => '05206', 'nombre' => 'Concepcion', 'departamento' => 'Antioquia'],
            ['id' => 48, 'codigo' => '05209', 'nombre' => 'Concordia', 'departamento' => 'Antioquia'],
            ['id' => 49, 'codigo' => '05212', 'nombre' => 'Copacabana', 'departamento' => 'Antioquia'],
            ['id' => 50, 'codigo' => '05234', 'nombre' => 'Dabeiba', 'departamento' => 'Antioquia'],
            ['id' => 51, 'codigo' => '05237', 'nombre' => 'Don Matias', 'departamento' => 'Antioquia'],
            ['id' => 52, 'codigo' => '05240', 'nombre' => 'Ebejico', 'departamento' => 'Antioquia'],
            ['id' => 53, 'codigo' => '05250', 'nombre' => 'El Bagre', 'departamento' => 'Antioquia'],
            ['id' => 54, 'codigo' => '05148', 'nombre' => 'El Carmen De Viboral', 'departamento' => 'Antioquia'],
            ['id' => 55, 'codigo' => '05697', 'nombre' => 'El Santuario', 'departamento' => 'Antioquia'],
            ['id' => 56, 'codigo' => '05264', 'nombre' => 'Entrerrios', 'departamento' => 'Antioquia'],
            ['id' => 57, 'codigo' => '05266', 'nombre' => 'Envigado', 'departamento' => 'Antioquia'],
            ['id' => 58, 'codigo' => '05282', 'nombre' => 'Fredonia', 'departamento' => 'Antioquia'],
            ['id' => 59, 'codigo' => '05284', 'nombre' => 'Frontino', 'departamento' => 'Antioquia'],
            ['id' => 60, 'codigo' => '05306', 'nombre' => 'Giraldo', 'departamento' => 'Antioquia'],
            ['id' => 61, 'codigo' => '05308', 'nombre' => 'Girardota', 'departamento' => 'Antioquia'],
            ['id' => 62, 'codigo' => '05310', 'nombre' => 'Gomez Plata', 'departamento' => 'Antioquia'],
            ['id' => 63, 'codigo' => '05313', 'nombre' => 'Granada', 'departamento' => 'Antioquia'],
            ['id' => 64, 'codigo' => '05315', 'nombre' => 'Guadalupe', 'departamento' => 'Antioquia'],
            ['id' => 65, 'codigo' => '05318', 'nombre' => 'Guarne', 'departamento' => 'Antioquia'],
            ['id' => 66, 'codigo' => '05321', 'nombre' => 'Guatape', 'departamento' => 'Antioquia'],
            ['id' => 67, 'codigo' => '05347', 'nombre' => 'Heliconia', 'departamento' => 'Antioquia'],
            ['id' => 68, 'codigo' => '05353', 'nombre' => 'Hispania', 'departamento' => 'Antioquia'],
            ['id' => 69, 'codigo' => '05360', 'nombre' => 'Itagüi', 'departamento' => 'Antioquia'],
            ['id' => 70, 'codigo' => '05361', 'nombre' => 'Ituango', 'departamento' => 'Antioquia'],
            ['id' => 71, 'codigo' => '05364', 'nombre' => 'Jardin', 'departamento' => 'Antioquia'],
            ['id' => 72, 'codigo' => '05368', 'nombre' => 'Jerico', 'departamento' => 'Antioquia'],
            ['id' => 73, 'codigo' => '05376', 'nombre' => 'La Ceja', 'departamento' => 'Antioquia'],
            ['id' => 74, 'codigo' => '05380', 'nombre' => 'La Estrella', 'departamento' => 'Antioquia'],
            ['id' => 75, 'codigo' => '05390', 'nombre' => 'La Pintada', 'departamento' => 'Antioquia'],
            ['id' => 76, 'codigo' => '05400', 'nombre' => 'La Union', 'departamento' => 'Antioquia'],
            ['id' => 77, 'codigo' => '05411', 'nombre' => 'Liborina', 'departamento' => 'Antioquia'],
            ['id' => 78, 'codigo' => '05425', 'nombre' => 'Maceo', 'departamento' => 'Antioquia'],
            ['id' => 79, 'codigo' => '05440', 'nombre' => 'Marinilla', 'departamento' => 'Antioquia'],
            ['id' => 80, 'codigo' => '05001', 'nombre' => 'Medellin', 'departamento' => 'Antioquia'],
            ['id' => 81, 'codigo' => '05467', 'nombre' => 'Montebello', 'departamento' => 'Antioquia'],
            ['id' => 82, 'codigo' => '05475', 'nombre' => 'Murindo', 'departamento' => 'Antioquia'],
            ['id' => 83, 'codigo' => '05480', 'nombre' => 'Mutata', 'departamento' => 'Antioquia'],
            ['id' => 84, 'codigo' => '05483', 'nombre' => 'Nariño', 'departamento' => 'Antioquia'],
            ['id' => 85, 'codigo' => '05495', 'nombre' => 'Nechi', 'departamento' => 'Antioquia'],
            ['id' => 86, 'codigo' => '05490', 'nombre' => 'Necocli', 'departamento' => 'Antioquia'],
            ['id' => 87, 'codigo' => '05501', 'nombre' => 'Olaya', 'departamento' => 'Antioquia'],
            ['id' => 88, 'codigo' => '05541', 'nombre' => 'Peñol', 'departamento' => 'Antioquia'],
            ['id' => 89, 'codigo' => '05543', 'nombre' => 'Peque', 'departamento' => 'Antioquia'],
            ['id' => 90, 'codigo' => '05576', 'nombre' => 'Pueblorrico', 'departamento' => 'Antioquia'],
            ['id' => 91, 'codigo' => '05579', 'nombre' => 'Puerto Berrio', 'departamento' => 'Antioquia'],
            ['id' => 92, 'codigo' => '05585', 'nombre' => 'Puerto Nare', 'departamento' => 'Antioquia'],
            ['id' => 93, 'codigo' => '05591', 'nombre' => 'Puerto Triunfo', 'departamento' => 'Antioquia'],
            ['id' => 94, 'codigo' => '05604', 'nombre' => 'Remedios', 'departamento' => 'Antioquia'],
            ['id' => 95, 'codigo' => '05607', 'nombre' => 'Retiro', 'departamento' => 'Antioquia'],
            ['id' => 96, 'codigo' => '05615', 'nombre' => 'Rionegro', 'departamento' => 'Antioquia'],
            ['id' => 97, 'codigo' => '05628', 'nombre' => 'Sabanalarga', 'departamento' => 'Antioquia'],
            ['id' => 98, 'codigo' => '05631', 'nombre' => 'Sabaneta', 'departamento' => 'Antioquia'],
            ['id' => 99, 'codigo' => '05642', 'nombre' => 'Salgar', 'departamento' => 'Antioquia'],
            ['id' => 100, 'codigo' => '05647', 'nombre' => 'San Andres De Cuerquia', 'departamento' => 'Antioquia'],
            ['id' => 101, 'codigo' => '05649', 'nombre' => 'San Carlos', 'departamento' => 'Antioquia'],
            ['id' => 102, 'codigo' => '05652', 'nombre' => 'San Francisco', 'departamento' => 'Antioquia'],
            ['id' => 103, 'codigo' => '05656', 'nombre' => 'San Jeronimo', 'departamento' => 'Antioquia'],
            ['id' => 104, 'codigo' => '05658', 'nombre' => 'San Jose De La Montaña', 'departamento' => 'Antioquia'],
            ['id' => 105, 'codigo' => '05659', 'nombre' => 'San Juan De Uraba', 'departamento' => 'Antioquia'],
            ['id' => 106, 'codigo' => '05660', 'nombre' => 'San Luis', 'departamento' => 'Antioquia'],
            ['id' => 107, 'codigo' => '05664', 'nombre' => 'San Pedro De Los Milagros', 'departamento' => 'Antioquia'],
            ['id' => 108, 'codigo' => '05665', 'nombre' => 'San Pedro De Uraba', 'departamento' => 'Antioquia'],
            ['id' => 109, 'codigo' => '05667', 'nombre' => 'San Rafael', 'departamento' => 'Antioquia'],
            ['id' => 110, 'codigo' => '05670', 'nombre' => 'San Roque', 'departamento' => 'Antioquia'],
            ['id' => 111, 'codigo' => '05674', 'nombre' => 'San Vicente', 'departamento' => 'Antioquia'],
            ['id' => 112, 'codigo' => '05679', 'nombre' => 'Santa Barbara', 'departamento' => 'Antioquia'],
            ['id' => 113, 'codigo' => '05686', 'nombre' => 'Santa Rosa De Osos', 'departamento' => 'Antioquia'],
            ['id' => 114, 'codigo' => '05042', 'nombre' => 'Santafe De Antioquia', 'departamento' => 'Antioquia'],
            ['id' => 115, 'codigo' => '05690', 'nombre' => 'Santo Domingo', 'departamento' => 'Antioquia'],
            ['id' => 116, 'codigo' => '05736', 'nombre' => 'Segovia', 'departamento' => 'Antioquia'],
            ['id' => 117, 'codigo' => '05756', 'nombre' => 'Sonson', 'departamento' => 'Antioquia'],
            ['id' => 118, 'codigo' => '05761', 'nombre' => 'Sopetran', 'departamento' => 'Antioquia'],
            ['id' => 119, 'codigo' => '05789', 'nombre' => 'Tamesis', 'departamento' => 'Antioquia'],
            ['id' => 120, 'codigo' => '05790', 'nombre' => 'Taraza', 'departamento' => 'Antioquia'],
            ['id' => 121, 'codigo' => '05792', 'nombre' => 'Tarso', 'departamento' => 'Antioquia'],
            ['id' => 122, 'codigo' => '05809', 'nombre' => 'Titiribi', 'departamento' => 'Antioquia'],
            ['id' => 123, 'codigo' => '05819', 'nombre' => 'Toledo', 'departamento' => 'Antioquia'],
            ['id' => 124, 'codigo' => '05837', 'nombre' => 'Turbo', 'departamento' => 'Antioquia'],
            ['id' => 125, 'codigo' => '05842', 'nombre' => 'Uramita', 'departamento' => 'Antioquia'],
            ['id' => 126, 'codigo' => '05847', 'nombre' => 'Urrao', 'departamento' => 'Antioquia'],
            ['id' => 127, 'codigo' => '05854', 'nombre' => 'Valdivia', 'departamento' => 'Antioquia'],
            ['id' => 128, 'codigo' => '05856', 'nombre' => 'Valparaiso', 'departamento' => 'Antioquia'],
            ['id' => 129, 'codigo' => '05858', 'nombre' => 'Vegachi', 'departamento' => 'Antioquia'],
            ['id' => 130, 'codigo' => '05861', 'nombre' => 'Venecia', 'departamento' => 'Antioquia'],
            ['id' => 131, 'codigo' => '05873', 'nombre' => 'Vigia Del Fuerte', 'departamento' => 'Antioquia'],
            ['id' => 132, 'codigo' => '05885', 'nombre' => 'Yali', 'departamento' => 'Antioquia'],
            ['id' => 133, 'codigo' => '05887', 'nombre' => 'Yarumal', 'departamento' => 'Antioquia'],
            ['id' => 134, 'codigo' => '05890', 'nombre' => 'Yolombo', 'departamento' => 'Antioquia'],
            ['id' => 135, 'codigo' => '05893', 'nombre' => 'Yondo', 'departamento' => 'Antioquia'],
            ['id' => 136, 'codigo' => '05895', 'nombre' => 'Zaragoza', 'departamento' => 'Antioquia'],
            ['id' => 499, 'codigo' => '23068', 'nombre' => 'Ayapel', 'departamento' => 'Cordoba'],
            ['id' => 500, 'codigo' => '23079', 'nombre' => 'Buenavista', 'departamento' => 'Cordoba'],
            ['id' => 501, 'codigo' => '23090', 'nombre' => 'Canalete', 'departamento' => 'Cordoba'],
            ['id' => 502, 'codigo' => '23162', 'nombre' => 'Cerete', 'departamento' => 'Cordoba'],
            ['id' => 503, 'codigo' => '23168', 'nombre' => 'Chima', 'departamento' => 'Cordoba'],
            ['id' => 504, 'codigo' => '23182', 'nombre' => 'Chinu', 'departamento' => 'Cordoba'],
            ['id' => 505, 'codigo' => '23189', 'nombre' => 'Cienaga De Oro', 'departamento' => 'Cordoba'],
            ['id' => 506, 'codigo' => '23300', 'nombre' => 'Cotorra', 'departamento' => 'Cordoba'],
            ['id' => 507, 'codigo' => '23350', 'nombre' => 'La Apartada', 'departamento' => 'Cordoba'],
            ['id' => 508, 'codigo' => '23417', 'nombre' => 'Lorica', 'departamento' => 'Cordoba'],
            ['id' => 509, 'codigo' => '23419', 'nombre' => 'Los Cordobas', 'departamento' => 'Cordoba'],
            ['id' => 510, 'codigo' => '23464', 'nombre' => 'Momil', 'departamento' => 'Cordoba'],
            ['id' => 511, 'codigo' => '23466', 'nombre' => 'Montelibano', 'departamento' => 'Cordoba'],
            ['id' => 512, 'codigo' => '23001', 'nombre' => 'Monteria', 'departamento' => 'Cordoba'],
            ['id' => 513, 'codigo' => '23500', 'nombre' => 'Moñitos', 'departamento' => 'Cordoba'],
            ['id' => 514, 'codigo' => '23555', 'nombre' => 'Planeta Rica', 'departamento' => 'Cordoba'],
            ['id' => 515, 'codigo' => '23570', 'nombre' => 'Pueblo Nuevo', 'departamento' => 'Cordoba'],
            ['id' => 516, 'codigo' => '23574', 'nombre' => 'Puerto Escondido', 'departamento' => 'Cordoba'],
            ['id' => 517, 'codigo' => '23580', 'nombre' => 'Puerto Libertador', 'departamento' => 'Cordoba'],
            ['id' => 518, 'codigo' => '23586', 'nombre' => 'Purisima', 'departamento' => 'Cordoba'],
            ['id' => 519, 'codigo' => '23660', 'nombre' => 'Sahagun', 'departamento' => 'Cordoba'],
            ['id' => 520, 'codigo' => '23670', 'nombre' => 'San Andres Sotavento', 'departamento' => 'Cordoba'],
            ['id' => 521, 'codigo' => '23672', 'nombre' => 'San Antero', 'departamento' => 'Cordoba'],
            ['id' => 522, 'codigo' => '23675', 'nombre' => 'San Bernardo Del Viento', 'departamento' => 'Cordoba'],
            ['id' => 523, 'codigo' => '23678', 'nombre' => 'San Carlos', 'departamento' => 'Cordoba'],
            ['id' => 524, 'codigo' => '23682', 'nombre' => 'San Jose De Ure', 'departamento' => 'Cordoba'],
            ['id' => 525, 'codigo' => '23686', 'nombre' => 'San Pelayo', 'departamento' => 'Cordoba'],
            ['id' => 526, 'codigo' => '23807', 'nombre' => 'Tierralta', 'departamento' => 'Cordoba'],
            ['id' => 527, 'codigo' => '23815', 'nombre' => 'Tuchin', 'departamento' => 'Cordoba'],
            ['id' => 528, 'codigo' => '23855', 'nombre' => 'Valencia', 'departamento' => 'Cordoba'],
        ]);
    }

    public function down(): void
    {
        Schema::dropIfExists('municipios');
    }
};
